version: '3.8'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    # image: mcr.microsoft.com/vscode/devcontainers/javascript-node:0-20-bullseye
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    ports:
      - "3000:3000"

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    # image: mcr.microsoft.com/vscode/devcontainers/javascript-node:0-20-bullseye
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    links:
      - frontend
    ports:
      - "5000:5000"

  dbPostgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
